server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_routh   #路由的ID
          #uri: http://localhost:8001         #匹配路由ID后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**           #断言，路径相匹配的进行路由
            - After=2022-04-10T16:43:20.503+08:00[Asia/Shanghai]

        - id: payment_routh2 #payment_routh   #路由的ID
          #uri: http://localhost:8001         #匹配路由ID后提供服务的路由地址
          uri: lb://cloud-payment-service
          #filters:
            #- AddRequestParamter=X-Request-Id,1024
          predicates:
            - Path=/payment/lb/**           #断言，路径相匹配的进行路由
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+
            #- Method=GET
            #- Query=username, \d+            #http:localhost:9527/payment/lb?username=123

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka